### ISSUE TITLE
Applicability of D.C. Law 15-194

### ISSUE THREAD

**Issue by bbryantdccouncil** [DCCouncil/dc-law-xml#108]
Where do I find this language so I can change it because it is very wrong:

Applicability of D.C. Law 15-194: § 656 of D.C. Law 15-194 provided that the the addition of this section by § 651 of D.C. Law 15-194 is subject to the inclusion of the law’s fiscal effect in an approved budget and financial plan. Therefore that amendment has not been given effect as of September 30, 2004.

**Comment by dgreisen** [comment]
This is using the default macro (https://github.com/DCCouncil/dc-law-xml/blob/master/.macros/codify_not_funded_anno.xml). We should discuss on Monday how to fix the macro to create the correct annotation.

**Comment by dgreisen** [comment]
Ben from #109: "I need to know how to changes the applicability of these sections as a group and individually. When I try to change 19-311.xml, nothing seems to happen or work."
