### ISSUE TITLE
Signed commits?

### ISSUE THREAD

**Issue by hrbrmstr** [DCCouncil/dc-law-xml#136]
Great article in Ars!

Any plans for Signed Commits? https://help.github.com/articles/signing-commits/

Provided there was a requirement that, say, all contributors must have something like a Keybase account (for extra verification of who they are) signed commits would enable better full attribution of who did what vs just relying on GH user ids.

**Comment by dgreisen** [comment]
Thanks for reaching out. We do not currently have plans to use git signing. There are a number of technical limitations, including metadata corruption, and user experience limitations, primarily around key management, that make git signing less than ideal. We will be rolling out a [UELMA-compliant](https://code.dccouncil.us/dc/council/code/titles/2/chapters/6/subchapters/V/) authentication scheme based on [TUF](https://theupdateframework.github.io/) in the next several months.
