### ISSUE TITLE
Add leading zero to single digit dc/council/periods?

### ISSUE THREAD

**Issue by RobRoseKnows** [DCCouncil/dc-law-xml#138]
Currently the directories under [dc/council/periods/](https://github.com/DCCouncil/dc-law-xml/tree/master/dc/council/periods) are all numbered 1, 2, 3, ..., 8, 9, 10, etc. This makes sense for text sorted by hand, but when this is displayed on GitHub and in other directories, it's sorted by the first digit meaning it shows up as: 1, 10, 11, ..., 19, 2, 20, ..., 4, 5, 6, 7, etc. The solution is to add a leading zero to the single digit periods. Is this something I can add as a PR or is there a reason it's done the way it is?

**Comment by bbryantdccouncil** [comment]
Thank you for your interest.  The numbering is set by law by the law makers of this jurisdiction and is not subject to change.

**Comment by RobRoseKnows** [comment]
Makes sense, thanks!
