### ISSUE TITLE
One commit per act possible?

### ISSUE THREAD

**Issue by mehmetaergun** [DCCouncil/dc-law-xml#152]
Is it possible for each commit to be associated with a single act, or other cohesive change, that could be described succinctly in the commit comments? This would help watching the changes and reviewing/understanding all the changes associated with that one cohesive unit (e.g. an act). 

Example: A single commit for all changes associated only with 23-134, where the commit title would be "Primary Date Alteration Amendment Act of 2019" (from commit https://github.com/DCCouncil/dc-law-xml/commit/f3c3c445bc03674dccf82208075ab81a3b4ddaf1#diff-f73e943e8f3fe924ea9d6f4c4dbb6db7)

**Comment by egyptiankarim** [comment]
@mehmetaergun's recommendation makes good sense and aligns with best practice for source-controlled content. Aspiring to make commits, and pull requests (i.e., bundled commits) as small and focused as possible helps to improve the experience of navigating change histories within a repository.

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">hey friendly reminder that the pull request you’re working on right this moment is way too big and you should cut it down into smaller pieces ✂️💓</p>&mdash; Zach Holman (@holman) <a href="https://twitter.com/holman/status/1017099922858901504?ref_src=twsrc%5Etfw">July 11, 2018</a></blockquote>
